# Site settings
author: Felipe Beltran
title: New beginnings in the World of Technology!
header-img: img/home-bg.png
email: felipebeltran.nyc@gmail.com
copyright_name: Felipe Beltran
description: > # this means to ignore newlines until "baseurl:"
  Challenges of a Code Newbie
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: FelipeBelieving
github_username:  Felipeb1003

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
